//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RandomRecipes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecipeStep
    {
        public int Recipe { get; set; }
        public int Sequence { get; set; }
        public string Step { get; set; }
    
        public virtual Recipe Recipe1 { get; set; }
    }
}
